### ISSUE TITLE
Add option to whether or not show domain structure

### ISSUE THREAD

**Issue by kaitoii11** [Medha-B/XitoSBML#14]
The input image for XitoSBMLcli could be more than 1 image. Thus, if we have 100 images as input, the domain structure of 100 images will be generated which could be annoying.
So, we should introduce a new boolean option to allow users to choose if they want to see the domain structure during their run.

**Comment by Medha-B** [comment]
I had actually kept ShowDomainStructure only to evaluate whether the CLI version produce some kind of errors in the domain structure. Do you mind if we removed ShowDomainStructure entirely from the CLI version? 
Also, I am not sure about how to do a boolean option with picocli.

**Comment by kaitoii11** [comment]
Either way is okay. But you are halfway there so you might as well implement it.

You could always look up the documents. 
https://picocli.info/#_boolean_options

**Comment by Medha-B** [comment]
Hello!
Please refer to the pull request https://github.com/Medha-B/XitoSBML/pull/18 for this issue and let me know if it looks alright.
