### ISSUE TITLE
Renaming path1 and path2 to imagePath and outputPath 

### ISSUE THREAD

**Issue by Medha-B** [Medha-B/XitoSBML#2]
Branch xitosbml_cui

**Comment by Medha-B** [comment]
Please see https://github.com/Medha-B/XitoSBML/pull/7.

**Comment by kaitoii11** [comment]
Next time, Add a link where the original discussion was(so for this one https://github.com/Medha-B/XitoSBML/pull/1#discussion_r467599943 ). So we have a reference to it and can jump right into the related code.
